# Generated by Django 3.0.6 on 2020-05-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('time', models.TimeField(default='00:00 AM')),
                ('date', models.DateField(default='2019-6-14')),
                ('start_position', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('max_members', models.PositiveIntegerField(default=4, help_text='maximum number of members includes you as well.')),
                ('gender', models.CharField(choices=[('all', 'all'), ('girls only', 'girls only'), ('boys only', 'boys only')], default='both', max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
