# Generated by Django 3.0.6 on 2020-05-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='gender',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='max_members',
            field=models.PositiveIntegerField(default=4, help_text='Including you.'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bookings.Bookings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
